package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.stereotype.Component;

import com.example.demo.model.Country;
import com.example.demo.model.Seller;
import com.example.demo.model.MenuItemCategory;
import com.example.demo.model.City;
import com.example.demo.model.SportShopBrand;
import com.example.demo.model.SportShop;
import com.example.demo.model.MenuItem;

import com.example.demo.service.CountryService;
import com.example.demo.service.SellerService;
import com.example.demo.service.MenuItemCategoryService;
import com.example.demo.service.CityService;
import com.example.demo.service.SportShopBrandService;
import com.example.demo.service.SportShopService;
import com.example.demo.service.MenuItemService;


@SpringBootApplication
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}

@Component
class DemoCommandLineRunner implements CommandLineRunner {
	
	@Autowired
	CountryService countryService;
	@Autowired
	SellerService sellerService;
	@Autowired
	MenuItemCategoryService menuItemCategoryService;
	@Autowired
	CityService cityService;
	@Autowired
	SportShopBrandService sportShopBrandService;
	@Autowired
	SportShopService sportShopService;
	@Autowired
	MenuItemService menuItemService;
	
	
	@Override
	public void run(String... arg0) throws Exception {
		
		// Country
		Country country1 = new Country();
		country1.setName("name1");
		countryService.save(country1);
		Country country2 = new Country();
		country2.setName("name2");
		countryService.save(country2);
		// Seller
		Seller seller1 = new Seller();
		seller1.setUsername("username1");
		seller1.setPassword("password1");
		seller1.setFirstName("firstName1");
		seller1.setLastName("lastName1");
		seller1.setEmail("email1");
		sellerService.save(seller1);
		Seller seller2 = new Seller();
		seller2.setUsername("username2");
		seller2.setPassword("password2");
		seller2.setFirstName("firstName2");
		seller2.setLastName("lastName2");
		seller2.setEmail("email2");
		sellerService.save(seller2);
		Seller seller3 = new Seller();
		seller3.setUsername("username3");
		seller3.setPassword("password3");
		seller3.setFirstName("firstName3");
		seller3.setLastName("lastName3");
		seller3.setEmail("email3");
		sellerService.save(seller3);
		Seller seller4 = new Seller();
		seller4.setUsername("username4");
		seller4.setPassword("password4");
		seller4.setFirstName("firstName4");
		seller4.setLastName("lastName4");
		seller4.setEmail("email4");
		sellerService.save(seller4);
		// MenuItemCategory
		MenuItemCategory menuItemCategory1 = new MenuItemCategory();
		menuItemCategory1.setName("name1");
		menuItemCategoryService.save(menuItemCategory1);
		MenuItemCategory menuItemCategory2 = new MenuItemCategory();
		menuItemCategory2.setName("name2");
		menuItemCategoryService.save(menuItemCategory2);
		MenuItemCategory menuItemCategory3 = new MenuItemCategory();
		menuItemCategory3.setName("name3");
		menuItemCategoryService.save(menuItemCategory3);
		MenuItemCategory menuItemCategory4 = new MenuItemCategory();
		menuItemCategory4.setName("name4");
		menuItemCategoryService.save(menuItemCategory4);
		MenuItemCategory menuItemCategory5 = new MenuItemCategory();
		menuItemCategory5.setName("name5");
		menuItemCategoryService.save(menuItemCategory5);
		MenuItemCategory menuItemCategory6 = new MenuItemCategory();
		menuItemCategory6.setName("name6");
		menuItemCategoryService.save(menuItemCategory6);
		MenuItemCategory menuItemCategory7 = new MenuItemCategory();
		menuItemCategory7.setName("name7");
		menuItemCategoryService.save(menuItemCategory7);
		MenuItemCategory menuItemCategory8 = new MenuItemCategory();
		menuItemCategory8.setName("name8");
		menuItemCategoryService.save(menuItemCategory8);
		// City
		City city1 = new City();
		city1.setName("name1");
		city1.setCountry(country1);
		cityService.save(city1);
		City city2 = new City();
		city2.setName("name2");
		city2.setCountry(country2);				
		cityService.save(city2);
		City city3 = new City();
		city3.setName("name3");
		city3.setCountry(country1);
		cityService.save(city3);
		City city4 = new City();
		city4.setName("name4");
		city4.setCountry(country2);				
		cityService.save(city4);
		City city5 = new City();
		city5.setName("name5");
		city5.setCountry(country1);
		cityService.save(city5);
		City city6 = new City();
		city6.setName("name6");
		city6.setCountry(country2);				
		cityService.save(city6);
		City city7 = new City();
		city7.setName("name7");
		city7.setCountry(country1);
		cityService.save(city7);
		City city8 = new City();
		city8.setName("name8");
		city8.setCountry(country2);				
		cityService.save(city8);
		City city9 = new City();
		city9.setName("name9");
		city9.setCountry(country1);
		cityService.save(city9);
		City city10 = new City();
		city10.setName("name10");
		city10.setCountry(country2);				
		cityService.save(city10);
		City city11 = new City();
		city11.setName("name11");
		city11.setCountry(country1);
		cityService.save(city11);
		City city12 = new City();
		city12.setName("name12");
		city12.setCountry(country2);				
		cityService.save(city12);
		City city13 = new City();
		city13.setName("name13");
		city13.setCountry(country1);
		cityService.save(city13);
		City city14 = new City();
		city14.setName("name14");
		city14.setCountry(country2);				
		cityService.save(city14);
		City city15 = new City();
		city15.setName("name15");
		city15.setCountry(country1);
		cityService.save(city15);
		City city16 = new City();
		city16.setName("name16");
		city16.setCountry(country2);				
		cityService.save(city16);
		// SportShopBrand
		SportShopBrand sportShopBrand1 = new SportShopBrand();
		sportShopBrand1.setName("name1");
		sportShopBrand1.setSeller(seller1);
		sportShopBrand1.setAdminComment("adminComment1");
		sportShopBrandService.save(sportShopBrand1);
		SportShopBrand sportShopBrand2 = new SportShopBrand();
		sportShopBrand2.setName("name2");
		sportShopBrand2.setSeller(seller2);				
		sportShopBrand2.setAdminComment("adminComment2");
		sportShopBrandService.save(sportShopBrand2);
		SportShopBrand sportShopBrand3 = new SportShopBrand();
		sportShopBrand3.setName("name3");
		sportShopBrand3.setSeller(seller1);
		sportShopBrand3.setAdminComment("adminComment3");
		sportShopBrandService.save(sportShopBrand3);
		SportShopBrand sportShopBrand4 = new SportShopBrand();
		sportShopBrand4.setName("name4");
		sportShopBrand4.setSeller(seller2);				
		sportShopBrand4.setAdminComment("adminComment4");
		sportShopBrandService.save(sportShopBrand4);
		SportShopBrand sportShopBrand5 = new SportShopBrand();
		sportShopBrand5.setName("name5");
		sportShopBrand5.setSeller(seller1);
		sportShopBrand5.setAdminComment("adminComment5");
		sportShopBrandService.save(sportShopBrand5);
		SportShopBrand sportShopBrand6 = new SportShopBrand();
		sportShopBrand6.setName("name6");
		sportShopBrand6.setSeller(seller2);				
		sportShopBrand6.setAdminComment("adminComment6");
		sportShopBrandService.save(sportShopBrand6);
		SportShopBrand sportShopBrand7 = new SportShopBrand();
		sportShopBrand7.setName("name7");
		sportShopBrand7.setSeller(seller1);
		sportShopBrand7.setAdminComment("adminComment7");
		sportShopBrandService.save(sportShopBrand7);
		SportShopBrand sportShopBrand8 = new SportShopBrand();
		sportShopBrand8.setName("name8");
		sportShopBrand8.setSeller(seller2);				
		sportShopBrand8.setAdminComment("adminComment8");
		sportShopBrandService.save(sportShopBrand8);
		SportShopBrand sportShopBrand9 = new SportShopBrand();
		sportShopBrand9.setName("name9");
		sportShopBrand9.setSeller(seller1);
		sportShopBrand9.setAdminComment("adminComment9");
		sportShopBrandService.save(sportShopBrand9);
		SportShopBrand sportShopBrand10 = new SportShopBrand();
		sportShopBrand10.setName("name10");
		sportShopBrand10.setSeller(seller2);				
		sportShopBrand10.setAdminComment("adminComment10");
		sportShopBrandService.save(sportShopBrand10);
		SportShopBrand sportShopBrand11 = new SportShopBrand();
		sportShopBrand11.setName("name11");
		sportShopBrand11.setSeller(seller1);
		sportShopBrand11.setAdminComment("adminComment11");
		sportShopBrandService.save(sportShopBrand11);
		SportShopBrand sportShopBrand12 = new SportShopBrand();
		sportShopBrand12.setName("name12");
		sportShopBrand12.setSeller(seller2);				
		sportShopBrand12.setAdminComment("adminComment12");
		sportShopBrandService.save(sportShopBrand12);
		SportShopBrand sportShopBrand13 = new SportShopBrand();
		sportShopBrand13.setName("name13");
		sportShopBrand13.setSeller(seller1);
		sportShopBrand13.setAdminComment("adminComment13");
		sportShopBrandService.save(sportShopBrand13);
		SportShopBrand sportShopBrand14 = new SportShopBrand();
		sportShopBrand14.setName("name14");
		sportShopBrand14.setSeller(seller2);				
		sportShopBrand14.setAdminComment("adminComment14");
		sportShopBrandService.save(sportShopBrand14);
		SportShopBrand sportShopBrand15 = new SportShopBrand();
		sportShopBrand15.setName("name15");
		sportShopBrand15.setSeller(seller1);
		sportShopBrand15.setAdminComment("adminComment15");
		sportShopBrandService.save(sportShopBrand15);
		SportShopBrand sportShopBrand16 = new SportShopBrand();
		sportShopBrand16.setName("name16");
		sportShopBrand16.setSeller(seller2);				
		sportShopBrand16.setAdminComment("adminComment16");
		sportShopBrandService.save(sportShopBrand16);
		SportShopBrand sportShopBrand17 = new SportShopBrand();
		sportShopBrand17.setName("name17");
		sportShopBrand17.setSeller(seller1);
		sportShopBrand17.setAdminComment("adminComment17");
		sportShopBrandService.save(sportShopBrand17);
		SportShopBrand sportShopBrand18 = new SportShopBrand();
		sportShopBrand18.setName("name18");
		sportShopBrand18.setSeller(seller2);				
		sportShopBrand18.setAdminComment("adminComment18");
		sportShopBrandService.save(sportShopBrand18);
		SportShopBrand sportShopBrand19 = new SportShopBrand();
		sportShopBrand19.setName("name19");
		sportShopBrand19.setSeller(seller1);
		sportShopBrand19.setAdminComment("adminComment19");
		sportShopBrandService.save(sportShopBrand19);
		SportShopBrand sportShopBrand20 = new SportShopBrand();
		sportShopBrand20.setName("name20");
		sportShopBrand20.setSeller(seller2);				
		sportShopBrand20.setAdminComment("adminComment20");
		sportShopBrandService.save(sportShopBrand20);
		SportShopBrand sportShopBrand21 = new SportShopBrand();
		sportShopBrand21.setName("name21");
		sportShopBrand21.setSeller(seller1);
		sportShopBrand21.setAdminComment("adminComment21");
		sportShopBrandService.save(sportShopBrand21);
		SportShopBrand sportShopBrand22 = new SportShopBrand();
		sportShopBrand22.setName("name22");
		sportShopBrand22.setSeller(seller2);				
		sportShopBrand22.setAdminComment("adminComment22");
		sportShopBrandService.save(sportShopBrand22);
		SportShopBrand sportShopBrand23 = new SportShopBrand();
		sportShopBrand23.setName("name23");
		sportShopBrand23.setSeller(seller1);
		sportShopBrand23.setAdminComment("adminComment23");
		sportShopBrandService.save(sportShopBrand23);
		SportShopBrand sportShopBrand24 = new SportShopBrand();
		sportShopBrand24.setName("name24");
		sportShopBrand24.setSeller(seller2);				
		sportShopBrand24.setAdminComment("adminComment24");
		sportShopBrandService.save(sportShopBrand24);
		SportShopBrand sportShopBrand25 = new SportShopBrand();
		sportShopBrand25.setName("name25");
		sportShopBrand25.setSeller(seller1);
		sportShopBrand25.setAdminComment("adminComment25");
		sportShopBrandService.save(sportShopBrand25);
		SportShopBrand sportShopBrand26 = new SportShopBrand();
		sportShopBrand26.setName("name26");
		sportShopBrand26.setSeller(seller2);				
		sportShopBrand26.setAdminComment("adminComment26");
		sportShopBrandService.save(sportShopBrand26);
		SportShopBrand sportShopBrand27 = new SportShopBrand();
		sportShopBrand27.setName("name27");
		sportShopBrand27.setSeller(seller1);
		sportShopBrand27.setAdminComment("adminComment27");
		sportShopBrandService.save(sportShopBrand27);
		SportShopBrand sportShopBrand28 = new SportShopBrand();
		sportShopBrand28.setName("name28");
		sportShopBrand28.setSeller(seller2);				
		sportShopBrand28.setAdminComment("adminComment28");
		sportShopBrandService.save(sportShopBrand28);
		SportShopBrand sportShopBrand29 = new SportShopBrand();
		sportShopBrand29.setName("name29");
		sportShopBrand29.setSeller(seller1);
		sportShopBrand29.setAdminComment("adminComment29");
		sportShopBrandService.save(sportShopBrand29);
		SportShopBrand sportShopBrand30 = new SportShopBrand();
		sportShopBrand30.setName("name30");
		sportShopBrand30.setSeller(seller2);				
		sportShopBrand30.setAdminComment("adminComment30");
		sportShopBrandService.save(sportShopBrand30);
		SportShopBrand sportShopBrand31 = new SportShopBrand();
		sportShopBrand31.setName("name31");
		sportShopBrand31.setSeller(seller1);
		sportShopBrand31.setAdminComment("adminComment31");
		sportShopBrandService.save(sportShopBrand31);
		SportShopBrand sportShopBrand32 = new SportShopBrand();
		sportShopBrand32.setName("name32");
		sportShopBrand32.setSeller(seller2);				
		sportShopBrand32.setAdminComment("adminComment32");
		sportShopBrandService.save(sportShopBrand32);
		// SportShop
		SportShop sportShop1 = new SportShop();
		sportShop1.setName("name1");
		sportShop1.setStreetName("streetName1");
		sportShop1.setStreetNumber(10);	
		sportShop1.setGpsLatitude(10.3);		
		sportShop1.setSportShopBrand(sportShopBrand1);
		sportShop1.setCity(city1);
		sportShop1.setGpsLongitude(10.3);		
		sportShopService.save(sportShop1);
		SportShop sportShop2 = new SportShop();
		sportShop2.setName("name2");
		sportShop2.setStreetName("streetName2");
		sportShop2.setStreetNumber(10);	
		sportShop2.setGpsLatitude(10.3);		
		sportShop2.setSportShopBrand(sportShopBrand2);				
		sportShop2.setCity(city2);				
		sportShop2.setGpsLongitude(10.3);		
		sportShopService.save(sportShop2);
		SportShop sportShop3 = new SportShop();
		sportShop3.setName("name3");
		sportShop3.setStreetName("streetName3");
		sportShop3.setStreetNumber(10);	
		sportShop3.setGpsLatitude(10.3);		
		sportShop3.setSportShopBrand(sportShopBrand1);
		sportShop3.setCity(city1);
		sportShop3.setGpsLongitude(10.3);		
		sportShopService.save(sportShop3);
		SportShop sportShop4 = new SportShop();
		sportShop4.setName("name4");
		sportShop4.setStreetName("streetName4");
		sportShop4.setStreetNumber(10);	
		sportShop4.setGpsLatitude(10.3);		
		sportShop4.setSportShopBrand(sportShopBrand2);				
		sportShop4.setCity(city2);				
		sportShop4.setGpsLongitude(10.3);		
		sportShopService.save(sportShop4);
		SportShop sportShop5 = new SportShop();
		sportShop5.setName("name5");
		sportShop5.setStreetName("streetName5");
		sportShop5.setStreetNumber(10);	
		sportShop5.setGpsLatitude(10.3);		
		sportShop5.setSportShopBrand(sportShopBrand1);
		sportShop5.setCity(city1);
		sportShop5.setGpsLongitude(10.3);		
		sportShopService.save(sportShop5);
		SportShop sportShop6 = new SportShop();
		sportShop6.setName("name6");
		sportShop6.setStreetName("streetName6");
		sportShop6.setStreetNumber(10);	
		sportShop6.setGpsLatitude(10.3);		
		sportShop6.setSportShopBrand(sportShopBrand2);				
		sportShop6.setCity(city2);				
		sportShop6.setGpsLongitude(10.3);		
		sportShopService.save(sportShop6);
		SportShop sportShop7 = new SportShop();
		sportShop7.setName("name7");
		sportShop7.setStreetName("streetName7");
		sportShop7.setStreetNumber(10);	
		sportShop7.setGpsLatitude(10.3);		
		sportShop7.setSportShopBrand(sportShopBrand1);
		sportShop7.setCity(city1);
		sportShop7.setGpsLongitude(10.3);		
		sportShopService.save(sportShop7);
		SportShop sportShop8 = new SportShop();
		sportShop8.setName("name8");
		sportShop8.setStreetName("streetName8");
		sportShop8.setStreetNumber(10);	
		sportShop8.setGpsLatitude(10.3);		
		sportShop8.setSportShopBrand(sportShopBrand2);				
		sportShop8.setCity(city2);				
		sportShop8.setGpsLongitude(10.3);		
		sportShopService.save(sportShop8);
		SportShop sportShop9 = new SportShop();
		sportShop9.setName("name9");
		sportShop9.setStreetName("streetName9");
		sportShop9.setStreetNumber(10);	
		sportShop9.setGpsLatitude(10.3);		
		sportShop9.setSportShopBrand(sportShopBrand1);
		sportShop9.setCity(city1);
		sportShop9.setGpsLongitude(10.3);		
		sportShopService.save(sportShop9);
		SportShop sportShop10 = new SportShop();
		sportShop10.setName("name10");
		sportShop10.setStreetName("streetName10");
		sportShop10.setStreetNumber(10);	
		sportShop10.setGpsLatitude(10.3);		
		sportShop10.setSportShopBrand(sportShopBrand2);				
		sportShop10.setCity(city2);				
		sportShop10.setGpsLongitude(10.3);		
		sportShopService.save(sportShop10);
		SportShop sportShop11 = new SportShop();
		sportShop11.setName("name11");
		sportShop11.setStreetName("streetName11");
		sportShop11.setStreetNumber(10);	
		sportShop11.setGpsLatitude(10.3);		
		sportShop11.setSportShopBrand(sportShopBrand1);
		sportShop11.setCity(city1);
		sportShop11.setGpsLongitude(10.3);		
		sportShopService.save(sportShop11);
		SportShop sportShop12 = new SportShop();
		sportShop12.setName("name12");
		sportShop12.setStreetName("streetName12");
		sportShop12.setStreetNumber(10);	
		sportShop12.setGpsLatitude(10.3);		
		sportShop12.setSportShopBrand(sportShopBrand2);				
		sportShop12.setCity(city2);				
		sportShop12.setGpsLongitude(10.3);		
		sportShopService.save(sportShop12);
		SportShop sportShop13 = new SportShop();
		sportShop13.setName("name13");
		sportShop13.setStreetName("streetName13");
		sportShop13.setStreetNumber(10);	
		sportShop13.setGpsLatitude(10.3);		
		sportShop13.setSportShopBrand(sportShopBrand1);
		sportShop13.setCity(city1);
		sportShop13.setGpsLongitude(10.3);		
		sportShopService.save(sportShop13);
		SportShop sportShop14 = new SportShop();
		sportShop14.setName("name14");
		sportShop14.setStreetName("streetName14");
		sportShop14.setStreetNumber(10);	
		sportShop14.setGpsLatitude(10.3);		
		sportShop14.setSportShopBrand(sportShopBrand2);				
		sportShop14.setCity(city2);				
		sportShop14.setGpsLongitude(10.3);		
		sportShopService.save(sportShop14);
		SportShop sportShop15 = new SportShop();
		sportShop15.setName("name15");
		sportShop15.setStreetName("streetName15");
		sportShop15.setStreetNumber(10);	
		sportShop15.setGpsLatitude(10.3);		
		sportShop15.setSportShopBrand(sportShopBrand1);
		sportShop15.setCity(city1);
		sportShop15.setGpsLongitude(10.3);		
		sportShopService.save(sportShop15);
		SportShop sportShop16 = new SportShop();
		sportShop16.setName("name16");
		sportShop16.setStreetName("streetName16");
		sportShop16.setStreetNumber(10);	
		sportShop16.setGpsLatitude(10.3);		
		sportShop16.setSportShopBrand(sportShopBrand2);				
		sportShop16.setCity(city2);				
		sportShop16.setGpsLongitude(10.3);		
		sportShopService.save(sportShop16);
		SportShop sportShop17 = new SportShop();
		sportShop17.setName("name17");
		sportShop17.setStreetName("streetName17");
		sportShop17.setStreetNumber(10);	
		sportShop17.setGpsLatitude(10.3);		
		sportShop17.setSportShopBrand(sportShopBrand1);
		sportShop17.setCity(city1);
		sportShop17.setGpsLongitude(10.3);		
		sportShopService.save(sportShop17);
		SportShop sportShop18 = new SportShop();
		sportShop18.setName("name18");
		sportShop18.setStreetName("streetName18");
		sportShop18.setStreetNumber(10);	
		sportShop18.setGpsLatitude(10.3);		
		sportShop18.setSportShopBrand(sportShopBrand2);				
		sportShop18.setCity(city2);				
		sportShop18.setGpsLongitude(10.3);		
		sportShopService.save(sportShop18);
		SportShop sportShop19 = new SportShop();
		sportShop19.setName("name19");
		sportShop19.setStreetName("streetName19");
		sportShop19.setStreetNumber(10);	
		sportShop19.setGpsLatitude(10.3);		
		sportShop19.setSportShopBrand(sportShopBrand1);
		sportShop19.setCity(city1);
		sportShop19.setGpsLongitude(10.3);		
		sportShopService.save(sportShop19);
		SportShop sportShop20 = new SportShop();
		sportShop20.setName("name20");
		sportShop20.setStreetName("streetName20");
		sportShop20.setStreetNumber(10);	
		sportShop20.setGpsLatitude(10.3);		
		sportShop20.setSportShopBrand(sportShopBrand2);				
		sportShop20.setCity(city2);				
		sportShop20.setGpsLongitude(10.3);		
		sportShopService.save(sportShop20);
		SportShop sportShop21 = new SportShop();
		sportShop21.setName("name21");
		sportShop21.setStreetName("streetName21");
		sportShop21.setStreetNumber(10);	
		sportShop21.setGpsLatitude(10.3);		
		sportShop21.setSportShopBrand(sportShopBrand1);
		sportShop21.setCity(city1);
		sportShop21.setGpsLongitude(10.3);		
		sportShopService.save(sportShop21);
		SportShop sportShop22 = new SportShop();
		sportShop22.setName("name22");
		sportShop22.setStreetName("streetName22");
		sportShop22.setStreetNumber(10);	
		sportShop22.setGpsLatitude(10.3);		
		sportShop22.setSportShopBrand(sportShopBrand2);				
		sportShop22.setCity(city2);				
		sportShop22.setGpsLongitude(10.3);		
		sportShopService.save(sportShop22);
		SportShop sportShop23 = new SportShop();
		sportShop23.setName("name23");
		sportShop23.setStreetName("streetName23");
		sportShop23.setStreetNumber(10);	
		sportShop23.setGpsLatitude(10.3);		
		sportShop23.setSportShopBrand(sportShopBrand1);
		sportShop23.setCity(city1);
		sportShop23.setGpsLongitude(10.3);		
		sportShopService.save(sportShop23);
		SportShop sportShop24 = new SportShop();
		sportShop24.setName("name24");
		sportShop24.setStreetName("streetName24");
		sportShop24.setStreetNumber(10);	
		sportShop24.setGpsLatitude(10.3);		
		sportShop24.setSportShopBrand(sportShopBrand2);				
		sportShop24.setCity(city2);				
		sportShop24.setGpsLongitude(10.3);		
		sportShopService.save(sportShop24);
		SportShop sportShop25 = new SportShop();
		sportShop25.setName("name25");
		sportShop25.setStreetName("streetName25");
		sportShop25.setStreetNumber(10);	
		sportShop25.setGpsLatitude(10.3);		
		sportShop25.setSportShopBrand(sportShopBrand1);
		sportShop25.setCity(city1);
		sportShop25.setGpsLongitude(10.3);		
		sportShopService.save(sportShop25);
		SportShop sportShop26 = new SportShop();
		sportShop26.setName("name26");
		sportShop26.setStreetName("streetName26");
		sportShop26.setStreetNumber(10);	
		sportShop26.setGpsLatitude(10.3);		
		sportShop26.setSportShopBrand(sportShopBrand2);				
		sportShop26.setCity(city2);				
		sportShop26.setGpsLongitude(10.3);		
		sportShopService.save(sportShop26);
		SportShop sportShop27 = new SportShop();
		sportShop27.setName("name27");
		sportShop27.setStreetName("streetName27");
		sportShop27.setStreetNumber(10);	
		sportShop27.setGpsLatitude(10.3);		
		sportShop27.setSportShopBrand(sportShopBrand1);
		sportShop27.setCity(city1);
		sportShop27.setGpsLongitude(10.3);		
		sportShopService.save(sportShop27);
		SportShop sportShop28 = new SportShop();
		sportShop28.setName("name28");
		sportShop28.setStreetName("streetName28");
		sportShop28.setStreetNumber(10);	
		sportShop28.setGpsLatitude(10.3);		
		sportShop28.setSportShopBrand(sportShopBrand2);				
		sportShop28.setCity(city2);				
		sportShop28.setGpsLongitude(10.3);		
		sportShopService.save(sportShop28);
		SportShop sportShop29 = new SportShop();
		sportShop29.setName("name29");
		sportShop29.setStreetName("streetName29");
		sportShop29.setStreetNumber(10);	
		sportShop29.setGpsLatitude(10.3);		
		sportShop29.setSportShopBrand(sportShopBrand1);
		sportShop29.setCity(city1);
		sportShop29.setGpsLongitude(10.3);		
		sportShopService.save(sportShop29);
		SportShop sportShop30 = new SportShop();
		sportShop30.setName("name30");
		sportShop30.setStreetName("streetName30");
		sportShop30.setStreetNumber(10);	
		sportShop30.setGpsLatitude(10.3);		
		sportShop30.setSportShopBrand(sportShopBrand2);				
		sportShop30.setCity(city2);				
		sportShop30.setGpsLongitude(10.3);		
		sportShopService.save(sportShop30);
		SportShop sportShop31 = new SportShop();
		sportShop31.setName("name31");
		sportShop31.setStreetName("streetName31");
		sportShop31.setStreetNumber(10);	
		sportShop31.setGpsLatitude(10.3);		
		sportShop31.setSportShopBrand(sportShopBrand1);
		sportShop31.setCity(city1);
		sportShop31.setGpsLongitude(10.3);		
		sportShopService.save(sportShop31);
		SportShop sportShop32 = new SportShop();
		sportShop32.setName("name32");
		sportShop32.setStreetName("streetName32");
		sportShop32.setStreetNumber(10);	
		sportShop32.setGpsLatitude(10.3);		
		sportShop32.setSportShopBrand(sportShopBrand2);				
		sportShop32.setCity(city2);				
		sportShop32.setGpsLongitude(10.3);		
		sportShopService.save(sportShop32);
		SportShop sportShop33 = new SportShop();
		sportShop33.setName("name33");
		sportShop33.setStreetName("streetName33");
		sportShop33.setStreetNumber(10);	
		sportShop33.setGpsLatitude(10.3);		
		sportShop33.setSportShopBrand(sportShopBrand1);
		sportShop33.setCity(city1);
		sportShop33.setGpsLongitude(10.3);		
		sportShopService.save(sportShop33);
		SportShop sportShop34 = new SportShop();
		sportShop34.setName("name34");
		sportShop34.setStreetName("streetName34");
		sportShop34.setStreetNumber(10);	
		sportShop34.setGpsLatitude(10.3);		
		sportShop34.setSportShopBrand(sportShopBrand2);				
		sportShop34.setCity(city2);				
		sportShop34.setGpsLongitude(10.3);		
		sportShopService.save(sportShop34);
		SportShop sportShop35 = new SportShop();
		sportShop35.setName("name35");
		sportShop35.setStreetName("streetName35");
		sportShop35.setStreetNumber(10);	
		sportShop35.setGpsLatitude(10.3);		
		sportShop35.setSportShopBrand(sportShopBrand1);
		sportShop35.setCity(city1);
		sportShop35.setGpsLongitude(10.3);		
		sportShopService.save(sportShop35);
		SportShop sportShop36 = new SportShop();
		sportShop36.setName("name36");
		sportShop36.setStreetName("streetName36");
		sportShop36.setStreetNumber(10);	
		sportShop36.setGpsLatitude(10.3);		
		sportShop36.setSportShopBrand(sportShopBrand2);				
		sportShop36.setCity(city2);				
		sportShop36.setGpsLongitude(10.3);		
		sportShopService.save(sportShop36);
		SportShop sportShop37 = new SportShop();
		sportShop37.setName("name37");
		sportShop37.setStreetName("streetName37");
		sportShop37.setStreetNumber(10);	
		sportShop37.setGpsLatitude(10.3);		
		sportShop37.setSportShopBrand(sportShopBrand1);
		sportShop37.setCity(city1);
		sportShop37.setGpsLongitude(10.3);		
		sportShopService.save(sportShop37);
		SportShop sportShop38 = new SportShop();
		sportShop38.setName("name38");
		sportShop38.setStreetName("streetName38");
		sportShop38.setStreetNumber(10);	
		sportShop38.setGpsLatitude(10.3);		
		sportShop38.setSportShopBrand(sportShopBrand2);				
		sportShop38.setCity(city2);				
		sportShop38.setGpsLongitude(10.3);		
		sportShopService.save(sportShop38);
		SportShop sportShop39 = new SportShop();
		sportShop39.setName("name39");
		sportShop39.setStreetName("streetName39");
		sportShop39.setStreetNumber(10);	
		sportShop39.setGpsLatitude(10.3);		
		sportShop39.setSportShopBrand(sportShopBrand1);
		sportShop39.setCity(city1);
		sportShop39.setGpsLongitude(10.3);		
		sportShopService.save(sportShop39);
		SportShop sportShop40 = new SportShop();
		sportShop40.setName("name40");
		sportShop40.setStreetName("streetName40");
		sportShop40.setStreetNumber(10);	
		sportShop40.setGpsLatitude(10.3);		
		sportShop40.setSportShopBrand(sportShopBrand2);				
		sportShop40.setCity(city2);				
		sportShop40.setGpsLongitude(10.3);		
		sportShopService.save(sportShop40);
		SportShop sportShop41 = new SportShop();
		sportShop41.setName("name41");
		sportShop41.setStreetName("streetName41");
		sportShop41.setStreetNumber(10);	
		sportShop41.setGpsLatitude(10.3);		
		sportShop41.setSportShopBrand(sportShopBrand1);
		sportShop41.setCity(city1);
		sportShop41.setGpsLongitude(10.3);		
		sportShopService.save(sportShop41);
		SportShop sportShop42 = new SportShop();
		sportShop42.setName("name42");
		sportShop42.setStreetName("streetName42");
		sportShop42.setStreetNumber(10);	
		sportShop42.setGpsLatitude(10.3);		
		sportShop42.setSportShopBrand(sportShopBrand2);				
		sportShop42.setCity(city2);				
		sportShop42.setGpsLongitude(10.3);		
		sportShopService.save(sportShop42);
		SportShop sportShop43 = new SportShop();
		sportShop43.setName("name43");
		sportShop43.setStreetName("streetName43");
		sportShop43.setStreetNumber(10);	
		sportShop43.setGpsLatitude(10.3);		
		sportShop43.setSportShopBrand(sportShopBrand1);
		sportShop43.setCity(city1);
		sportShop43.setGpsLongitude(10.3);		
		sportShopService.save(sportShop43);
		SportShop sportShop44 = new SportShop();
		sportShop44.setName("name44");
		sportShop44.setStreetName("streetName44");
		sportShop44.setStreetNumber(10);	
		sportShop44.setGpsLatitude(10.3);		
		sportShop44.setSportShopBrand(sportShopBrand2);				
		sportShop44.setCity(city2);				
		sportShop44.setGpsLongitude(10.3);		
		sportShopService.save(sportShop44);
		SportShop sportShop45 = new SportShop();
		sportShop45.setName("name45");
		sportShop45.setStreetName("streetName45");
		sportShop45.setStreetNumber(10);	
		sportShop45.setGpsLatitude(10.3);		
		sportShop45.setSportShopBrand(sportShopBrand1);
		sportShop45.setCity(city1);
		sportShop45.setGpsLongitude(10.3);		
		sportShopService.save(sportShop45);
		SportShop sportShop46 = new SportShop();
		sportShop46.setName("name46");
		sportShop46.setStreetName("streetName46");
		sportShop46.setStreetNumber(10);	
		sportShop46.setGpsLatitude(10.3);		
		sportShop46.setSportShopBrand(sportShopBrand2);				
		sportShop46.setCity(city2);				
		sportShop46.setGpsLongitude(10.3);		
		sportShopService.save(sportShop46);
		SportShop sportShop47 = new SportShop();
		sportShop47.setName("name47");
		sportShop47.setStreetName("streetName47");
		sportShop47.setStreetNumber(10);	
		sportShop47.setGpsLatitude(10.3);		
		sportShop47.setSportShopBrand(sportShopBrand1);
		sportShop47.setCity(city1);
		sportShop47.setGpsLongitude(10.3);		
		sportShopService.save(sportShop47);
		SportShop sportShop48 = new SportShop();
		sportShop48.setName("name48");
		sportShop48.setStreetName("streetName48");
		sportShop48.setStreetNumber(10);	
		sportShop48.setGpsLatitude(10.3);		
		sportShop48.setSportShopBrand(sportShopBrand2);				
		sportShop48.setCity(city2);				
		sportShop48.setGpsLongitude(10.3);		
		sportShopService.save(sportShop48);
		SportShop sportShop49 = new SportShop();
		sportShop49.setName("name49");
		sportShop49.setStreetName("streetName49");
		sportShop49.setStreetNumber(10);	
		sportShop49.setGpsLatitude(10.3);		
		sportShop49.setSportShopBrand(sportShopBrand1);
		sportShop49.setCity(city1);
		sportShop49.setGpsLongitude(10.3);		
		sportShopService.save(sportShop49);
		SportShop sportShop50 = new SportShop();
		sportShop50.setName("name50");
		sportShop50.setStreetName("streetName50");
		sportShop50.setStreetNumber(10);	
		sportShop50.setGpsLatitude(10.3);		
		sportShop50.setSportShopBrand(sportShopBrand2);				
		sportShop50.setCity(city2);				
		sportShop50.setGpsLongitude(10.3);		
		sportShopService.save(sportShop50);
		SportShop sportShop51 = new SportShop();
		sportShop51.setName("name51");
		sportShop51.setStreetName("streetName51");
		sportShop51.setStreetNumber(10);	
		sportShop51.setGpsLatitude(10.3);		
		sportShop51.setSportShopBrand(sportShopBrand1);
		sportShop51.setCity(city1);
		sportShop51.setGpsLongitude(10.3);		
		sportShopService.save(sportShop51);
		SportShop sportShop52 = new SportShop();
		sportShop52.setName("name52");
		sportShop52.setStreetName("streetName52");
		sportShop52.setStreetNumber(10);	
		sportShop52.setGpsLatitude(10.3);		
		sportShop52.setSportShopBrand(sportShopBrand2);				
		sportShop52.setCity(city2);				
		sportShop52.setGpsLongitude(10.3);		
		sportShopService.save(sportShop52);
		SportShop sportShop53 = new SportShop();
		sportShop53.setName("name53");
		sportShop53.setStreetName("streetName53");
		sportShop53.setStreetNumber(10);	
		sportShop53.setGpsLatitude(10.3);		
		sportShop53.setSportShopBrand(sportShopBrand1);
		sportShop53.setCity(city1);
		sportShop53.setGpsLongitude(10.3);		
		sportShopService.save(sportShop53);
		SportShop sportShop54 = new SportShop();
		sportShop54.setName("name54");
		sportShop54.setStreetName("streetName54");
		sportShop54.setStreetNumber(10);	
		sportShop54.setGpsLatitude(10.3);		
		sportShop54.setSportShopBrand(sportShopBrand2);				
		sportShop54.setCity(city2);				
		sportShop54.setGpsLongitude(10.3);		
		sportShopService.save(sportShop54);
		SportShop sportShop55 = new SportShop();
		sportShop55.setName("name55");
		sportShop55.setStreetName("streetName55");
		sportShop55.setStreetNumber(10);	
		sportShop55.setGpsLatitude(10.3);		
		sportShop55.setSportShopBrand(sportShopBrand1);
		sportShop55.setCity(city1);
		sportShop55.setGpsLongitude(10.3);		
		sportShopService.save(sportShop55);
		SportShop sportShop56 = new SportShop();
		sportShop56.setName("name56");
		sportShop56.setStreetName("streetName56");
		sportShop56.setStreetNumber(10);	
		sportShop56.setGpsLatitude(10.3);		
		sportShop56.setSportShopBrand(sportShopBrand2);				
		sportShop56.setCity(city2);				
		sportShop56.setGpsLongitude(10.3);		
		sportShopService.save(sportShop56);
		SportShop sportShop57 = new SportShop();
		sportShop57.setName("name57");
		sportShop57.setStreetName("streetName57");
		sportShop57.setStreetNumber(10);	
		sportShop57.setGpsLatitude(10.3);		
		sportShop57.setSportShopBrand(sportShopBrand1);
		sportShop57.setCity(city1);
		sportShop57.setGpsLongitude(10.3);		
		sportShopService.save(sportShop57);
		SportShop sportShop58 = new SportShop();
		sportShop58.setName("name58");
		sportShop58.setStreetName("streetName58");
		sportShop58.setStreetNumber(10);	
		sportShop58.setGpsLatitude(10.3);		
		sportShop58.setSportShopBrand(sportShopBrand2);				
		sportShop58.setCity(city2);				
		sportShop58.setGpsLongitude(10.3);		
		sportShopService.save(sportShop58);
		SportShop sportShop59 = new SportShop();
		sportShop59.setName("name59");
		sportShop59.setStreetName("streetName59");
		sportShop59.setStreetNumber(10);	
		sportShop59.setGpsLatitude(10.3);		
		sportShop59.setSportShopBrand(sportShopBrand1);
		sportShop59.setCity(city1);
		sportShop59.setGpsLongitude(10.3);		
		sportShopService.save(sportShop59);
		SportShop sportShop60 = new SportShop();
		sportShop60.setName("name60");
		sportShop60.setStreetName("streetName60");
		sportShop60.setStreetNumber(10);	
		sportShop60.setGpsLatitude(10.3);		
		sportShop60.setSportShopBrand(sportShopBrand2);				
		sportShop60.setCity(city2);				
		sportShop60.setGpsLongitude(10.3);		
		sportShopService.save(sportShop60);
		SportShop sportShop61 = new SportShop();
		sportShop61.setName("name61");
		sportShop61.setStreetName("streetName61");
		sportShop61.setStreetNumber(10);	
		sportShop61.setGpsLatitude(10.3);		
		sportShop61.setSportShopBrand(sportShopBrand1);
		sportShop61.setCity(city1);
		sportShop61.setGpsLongitude(10.3);		
		sportShopService.save(sportShop61);
		SportShop sportShop62 = new SportShop();
		sportShop62.setName("name62");
		sportShop62.setStreetName("streetName62");
		sportShop62.setStreetNumber(10);	
		sportShop62.setGpsLatitude(10.3);		
		sportShop62.setSportShopBrand(sportShopBrand2);				
		sportShop62.setCity(city2);				
		sportShop62.setGpsLongitude(10.3);		
		sportShopService.save(sportShop62);
		SportShop sportShop63 = new SportShop();
		sportShop63.setName("name63");
		sportShop63.setStreetName("streetName63");
		sportShop63.setStreetNumber(10);	
		sportShop63.setGpsLatitude(10.3);		
		sportShop63.setSportShopBrand(sportShopBrand1);
		sportShop63.setCity(city1);
		sportShop63.setGpsLongitude(10.3);		
		sportShopService.save(sportShop63);
		SportShop sportShop64 = new SportShop();
		sportShop64.setName("name64");
		sportShop64.setStreetName("streetName64");
		sportShop64.setStreetNumber(10);	
		sportShop64.setGpsLatitude(10.3);		
		sportShop64.setSportShopBrand(sportShopBrand2);				
		sportShop64.setCity(city2);				
		sportShop64.setGpsLongitude(10.3);		
		sportShopService.save(sportShop64);
		// MenuItem
		MenuItem menuItem1 = new MenuItem();
		menuItem1.setName("name1");
		menuItem1.setDescription("description1");
		menuItem1.setPrice(10.3);		
		menuItem1.setMenuItemCategory(menuItemCategory1);
		menuItem1.setSportShop(sportShop1);
		menuItemService.save(menuItem1);
		MenuItem menuItem2 = new MenuItem();
		menuItem2.setName("name2");
		menuItem2.setDescription("description2");
		menuItem2.setPrice(10.3);		
		menuItem2.setMenuItemCategory(menuItemCategory2);				
		menuItem2.setSportShop(sportShop2);				
		menuItemService.save(menuItem2);
		MenuItem menuItem3 = new MenuItem();
		menuItem3.setName("name3");
		menuItem3.setDescription("description3");
		menuItem3.setPrice(10.3);		
		menuItem3.setMenuItemCategory(menuItemCategory1);
		menuItem3.setSportShop(sportShop1);
		menuItemService.save(menuItem3);
		MenuItem menuItem4 = new MenuItem();
		menuItem4.setName("name4");
		menuItem4.setDescription("description4");
		menuItem4.setPrice(10.3);		
		menuItem4.setMenuItemCategory(menuItemCategory2);				
		menuItem4.setSportShop(sportShop2);				
		menuItemService.save(menuItem4);
		MenuItem menuItem5 = new MenuItem();
		menuItem5.setName("name5");
		menuItem5.setDescription("description5");
		menuItem5.setPrice(10.3);		
		menuItem5.setMenuItemCategory(menuItemCategory1);
		menuItem5.setSportShop(sportShop1);
		menuItemService.save(menuItem5);
		MenuItem menuItem6 = new MenuItem();
		menuItem6.setName("name6");
		menuItem6.setDescription("description6");
		menuItem6.setPrice(10.3);		
		menuItem6.setMenuItemCategory(menuItemCategory2);				
		menuItem6.setSportShop(sportShop2);				
		menuItemService.save(menuItem6);
		MenuItem menuItem7 = new MenuItem();
		menuItem7.setName("name7");
		menuItem7.setDescription("description7");
		menuItem7.setPrice(10.3);		
		menuItem7.setMenuItemCategory(menuItemCategory1);
		menuItem7.setSportShop(sportShop1);
		menuItemService.save(menuItem7);
		MenuItem menuItem8 = new MenuItem();
		menuItem8.setName("name8");
		menuItem8.setDescription("description8");
		menuItem8.setPrice(10.3);		
		menuItem8.setMenuItemCategory(menuItemCategory2);				
		menuItem8.setSportShop(sportShop2);				
		menuItemService.save(menuItem8);
		MenuItem menuItem9 = new MenuItem();
		menuItem9.setName("name9");
		menuItem9.setDescription("description9");
		menuItem9.setPrice(10.3);		
		menuItem9.setMenuItemCategory(menuItemCategory1);
		menuItem9.setSportShop(sportShop1);
		menuItemService.save(menuItem9);
		MenuItem menuItem10 = new MenuItem();
		menuItem10.setName("name10");
		menuItem10.setDescription("description10");
		menuItem10.setPrice(10.3);		
		menuItem10.setMenuItemCategory(menuItemCategory2);				
		menuItem10.setSportShop(sportShop2);				
		menuItemService.save(menuItem10);
		MenuItem menuItem11 = new MenuItem();
		menuItem11.setName("name11");
		menuItem11.setDescription("description11");
		menuItem11.setPrice(10.3);		
		menuItem11.setMenuItemCategory(menuItemCategory1);
		menuItem11.setSportShop(sportShop1);
		menuItemService.save(menuItem11);
		MenuItem menuItem12 = new MenuItem();
		menuItem12.setName("name12");
		menuItem12.setDescription("description12");
		menuItem12.setPrice(10.3);		
		menuItem12.setMenuItemCategory(menuItemCategory2);				
		menuItem12.setSportShop(sportShop2);				
		menuItemService.save(menuItem12);
		MenuItem menuItem13 = new MenuItem();
		menuItem13.setName("name13");
		menuItem13.setDescription("description13");
		menuItem13.setPrice(10.3);		
		menuItem13.setMenuItemCategory(menuItemCategory1);
		menuItem13.setSportShop(sportShop1);
		menuItemService.save(menuItem13);
		MenuItem menuItem14 = new MenuItem();
		menuItem14.setName("name14");
		menuItem14.setDescription("description14");
		menuItem14.setPrice(10.3);		
		menuItem14.setMenuItemCategory(menuItemCategory2);				
		menuItem14.setSportShop(sportShop2);				
		menuItemService.save(menuItem14);
		MenuItem menuItem15 = new MenuItem();
		menuItem15.setName("name15");
		menuItem15.setDescription("description15");
		menuItem15.setPrice(10.3);		
		menuItem15.setMenuItemCategory(menuItemCategory1);
		menuItem15.setSportShop(sportShop1);
		menuItemService.save(menuItem15);
		MenuItem menuItem16 = new MenuItem();
		menuItem16.setName("name16");
		menuItem16.setDescription("description16");
		menuItem16.setPrice(10.3);		
		menuItem16.setMenuItemCategory(menuItemCategory2);				
		menuItem16.setSportShop(sportShop2);				
		menuItemService.save(menuItem16);
		MenuItem menuItem17 = new MenuItem();
		menuItem17.setName("name17");
		menuItem17.setDescription("description17");
		menuItem17.setPrice(10.3);		
		menuItem17.setMenuItemCategory(menuItemCategory1);
		menuItem17.setSportShop(sportShop1);
		menuItemService.save(menuItem17);
		MenuItem menuItem18 = new MenuItem();
		menuItem18.setName("name18");
		menuItem18.setDescription("description18");
		menuItem18.setPrice(10.3);		
		menuItem18.setMenuItemCategory(menuItemCategory2);				
		menuItem18.setSportShop(sportShop2);				
		menuItemService.save(menuItem18);
		MenuItem menuItem19 = new MenuItem();
		menuItem19.setName("name19");
		menuItem19.setDescription("description19");
		menuItem19.setPrice(10.3);		
		menuItem19.setMenuItemCategory(menuItemCategory1);
		menuItem19.setSportShop(sportShop1);
		menuItemService.save(menuItem19);
		MenuItem menuItem20 = new MenuItem();
		menuItem20.setName("name20");
		menuItem20.setDescription("description20");
		menuItem20.setPrice(10.3);		
		menuItem20.setMenuItemCategory(menuItemCategory2);				
		menuItem20.setSportShop(sportShop2);				
		menuItemService.save(menuItem20);
		MenuItem menuItem21 = new MenuItem();
		menuItem21.setName("name21");
		menuItem21.setDescription("description21");
		menuItem21.setPrice(10.3);		
		menuItem21.setMenuItemCategory(menuItemCategory1);
		menuItem21.setSportShop(sportShop1);
		menuItemService.save(menuItem21);
		MenuItem menuItem22 = new MenuItem();
		menuItem22.setName("name22");
		menuItem22.setDescription("description22");
		menuItem22.setPrice(10.3);		
		menuItem22.setMenuItemCategory(menuItemCategory2);				
		menuItem22.setSportShop(sportShop2);				
		menuItemService.save(menuItem22);
		MenuItem menuItem23 = new MenuItem();
		menuItem23.setName("name23");
		menuItem23.setDescription("description23");
		menuItem23.setPrice(10.3);		
		menuItem23.setMenuItemCategory(menuItemCategory1);
		menuItem23.setSportShop(sportShop1);
		menuItemService.save(menuItem23);
		MenuItem menuItem24 = new MenuItem();
		menuItem24.setName("name24");
		menuItem24.setDescription("description24");
		menuItem24.setPrice(10.3);		
		menuItem24.setMenuItemCategory(menuItemCategory2);				
		menuItem24.setSportShop(sportShop2);				
		menuItemService.save(menuItem24);
		MenuItem menuItem25 = new MenuItem();
		menuItem25.setName("name25");
		menuItem25.setDescription("description25");
		menuItem25.setPrice(10.3);		
		menuItem25.setMenuItemCategory(menuItemCategory1);
		menuItem25.setSportShop(sportShop1);
		menuItemService.save(menuItem25);
		MenuItem menuItem26 = new MenuItem();
		menuItem26.setName("name26");
		menuItem26.setDescription("description26");
		menuItem26.setPrice(10.3);		
		menuItem26.setMenuItemCategory(menuItemCategory2);				
		menuItem26.setSportShop(sportShop2);				
		menuItemService.save(menuItem26);
		MenuItem menuItem27 = new MenuItem();
		menuItem27.setName("name27");
		menuItem27.setDescription("description27");
		menuItem27.setPrice(10.3);		
		menuItem27.setMenuItemCategory(menuItemCategory1);
		menuItem27.setSportShop(sportShop1);
		menuItemService.save(menuItem27);
		MenuItem menuItem28 = new MenuItem();
		menuItem28.setName("name28");
		menuItem28.setDescription("description28");
		menuItem28.setPrice(10.3);		
		menuItem28.setMenuItemCategory(menuItemCategory2);				
		menuItem28.setSportShop(sportShop2);				
		menuItemService.save(menuItem28);
		MenuItem menuItem29 = new MenuItem();
		menuItem29.setName("name29");
		menuItem29.setDescription("description29");
		menuItem29.setPrice(10.3);		
		menuItem29.setMenuItemCategory(menuItemCategory1);
		menuItem29.setSportShop(sportShop1);
		menuItemService.save(menuItem29);
		MenuItem menuItem30 = new MenuItem();
		menuItem30.setName("name30");
		menuItem30.setDescription("description30");
		menuItem30.setPrice(10.3);		
		menuItem30.setMenuItemCategory(menuItemCategory2);				
		menuItem30.setSportShop(sportShop2);				
		menuItemService.save(menuItem30);
		MenuItem menuItem31 = new MenuItem();
		menuItem31.setName("name31");
		menuItem31.setDescription("description31");
		menuItem31.setPrice(10.3);		
		menuItem31.setMenuItemCategory(menuItemCategory1);
		menuItem31.setSportShop(sportShop1);
		menuItemService.save(menuItem31);
		MenuItem menuItem32 = new MenuItem();
		menuItem32.setName("name32");
		menuItem32.setDescription("description32");
		menuItem32.setPrice(10.3);		
		menuItem32.setMenuItemCategory(menuItemCategory2);				
		menuItem32.setSportShop(sportShop2);				
		menuItemService.save(menuItem32);
		MenuItem menuItem33 = new MenuItem();
		menuItem33.setName("name33");
		menuItem33.setDescription("description33");
		menuItem33.setPrice(10.3);		
		menuItem33.setMenuItemCategory(menuItemCategory1);
		menuItem33.setSportShop(sportShop1);
		menuItemService.save(menuItem33);
		MenuItem menuItem34 = new MenuItem();
		menuItem34.setName("name34");
		menuItem34.setDescription("description34");
		menuItem34.setPrice(10.3);		
		menuItem34.setMenuItemCategory(menuItemCategory2);				
		menuItem34.setSportShop(sportShop2);				
		menuItemService.save(menuItem34);
		MenuItem menuItem35 = new MenuItem();
		menuItem35.setName("name35");
		menuItem35.setDescription("description35");
		menuItem35.setPrice(10.3);		
		menuItem35.setMenuItemCategory(menuItemCategory1);
		menuItem35.setSportShop(sportShop1);
		menuItemService.save(menuItem35);
		MenuItem menuItem36 = new MenuItem();
		menuItem36.setName("name36");
		menuItem36.setDescription("description36");
		menuItem36.setPrice(10.3);		
		menuItem36.setMenuItemCategory(menuItemCategory2);				
		menuItem36.setSportShop(sportShop2);				
		menuItemService.save(menuItem36);
		MenuItem menuItem37 = new MenuItem();
		menuItem37.setName("name37");
		menuItem37.setDescription("description37");
		menuItem37.setPrice(10.3);		
		menuItem37.setMenuItemCategory(menuItemCategory1);
		menuItem37.setSportShop(sportShop1);
		menuItemService.save(menuItem37);
		MenuItem menuItem38 = new MenuItem();
		menuItem38.setName("name38");
		menuItem38.setDescription("description38");
		menuItem38.setPrice(10.3);		
		menuItem38.setMenuItemCategory(menuItemCategory2);				
		menuItem38.setSportShop(sportShop2);				
		menuItemService.save(menuItem38);
		MenuItem menuItem39 = new MenuItem();
		menuItem39.setName("name39");
		menuItem39.setDescription("description39");
		menuItem39.setPrice(10.3);		
		menuItem39.setMenuItemCategory(menuItemCategory1);
		menuItem39.setSportShop(sportShop1);
		menuItemService.save(menuItem39);
		MenuItem menuItem40 = new MenuItem();
		menuItem40.setName("name40");
		menuItem40.setDescription("description40");
		menuItem40.setPrice(10.3);		
		menuItem40.setMenuItemCategory(menuItemCategory2);				
		menuItem40.setSportShop(sportShop2);				
		menuItemService.save(menuItem40);
		MenuItem menuItem41 = new MenuItem();
		menuItem41.setName("name41");
		menuItem41.setDescription("description41");
		menuItem41.setPrice(10.3);		
		menuItem41.setMenuItemCategory(menuItemCategory1);
		menuItem41.setSportShop(sportShop1);
		menuItemService.save(menuItem41);
		MenuItem menuItem42 = new MenuItem();
		menuItem42.setName("name42");
		menuItem42.setDescription("description42");
		menuItem42.setPrice(10.3);		
		menuItem42.setMenuItemCategory(menuItemCategory2);				
		menuItem42.setSportShop(sportShop2);				
		menuItemService.save(menuItem42);
		MenuItem menuItem43 = new MenuItem();
		menuItem43.setName("name43");
		menuItem43.setDescription("description43");
		menuItem43.setPrice(10.3);		
		menuItem43.setMenuItemCategory(menuItemCategory1);
		menuItem43.setSportShop(sportShop1);
		menuItemService.save(menuItem43);
		MenuItem menuItem44 = new MenuItem();
		menuItem44.setName("name44");
		menuItem44.setDescription("description44");
		menuItem44.setPrice(10.3);		
		menuItem44.setMenuItemCategory(menuItemCategory2);				
		menuItem44.setSportShop(sportShop2);				
		menuItemService.save(menuItem44);
		MenuItem menuItem45 = new MenuItem();
		menuItem45.setName("name45");
		menuItem45.setDescription("description45");
		menuItem45.setPrice(10.3);		
		menuItem45.setMenuItemCategory(menuItemCategory1);
		menuItem45.setSportShop(sportShop1);
		menuItemService.save(menuItem45);
		MenuItem menuItem46 = new MenuItem();
		menuItem46.setName("name46");
		menuItem46.setDescription("description46");
		menuItem46.setPrice(10.3);		
		menuItem46.setMenuItemCategory(menuItemCategory2);				
		menuItem46.setSportShop(sportShop2);				
		menuItemService.save(menuItem46);
		MenuItem menuItem47 = new MenuItem();
		menuItem47.setName("name47");
		menuItem47.setDescription("description47");
		menuItem47.setPrice(10.3);		
		menuItem47.setMenuItemCategory(menuItemCategory1);
		menuItem47.setSportShop(sportShop1);
		menuItemService.save(menuItem47);
		MenuItem menuItem48 = new MenuItem();
		menuItem48.setName("name48");
		menuItem48.setDescription("description48");
		menuItem48.setPrice(10.3);		
		menuItem48.setMenuItemCategory(menuItemCategory2);				
		menuItem48.setSportShop(sportShop2);				
		menuItemService.save(menuItem48);
		MenuItem menuItem49 = new MenuItem();
		menuItem49.setName("name49");
		menuItem49.setDescription("description49");
		menuItem49.setPrice(10.3);		
		menuItem49.setMenuItemCategory(menuItemCategory1);
		menuItem49.setSportShop(sportShop1);
		menuItemService.save(menuItem49);
		MenuItem menuItem50 = new MenuItem();
		menuItem50.setName("name50");
		menuItem50.setDescription("description50");
		menuItem50.setPrice(10.3);		
		menuItem50.setMenuItemCategory(menuItemCategory2);				
		menuItem50.setSportShop(sportShop2);				
		menuItemService.save(menuItem50);
		MenuItem menuItem51 = new MenuItem();
		menuItem51.setName("name51");
		menuItem51.setDescription("description51");
		menuItem51.setPrice(10.3);		
		menuItem51.setMenuItemCategory(menuItemCategory1);
		menuItem51.setSportShop(sportShop1);
		menuItemService.save(menuItem51);
		MenuItem menuItem52 = new MenuItem();
		menuItem52.setName("name52");
		menuItem52.setDescription("description52");
		menuItem52.setPrice(10.3);		
		menuItem52.setMenuItemCategory(menuItemCategory2);				
		menuItem52.setSportShop(sportShop2);				
		menuItemService.save(menuItem52);
		MenuItem menuItem53 = new MenuItem();
		menuItem53.setName("name53");
		menuItem53.setDescription("description53");
		menuItem53.setPrice(10.3);		
		menuItem53.setMenuItemCategory(menuItemCategory1);
		menuItem53.setSportShop(sportShop1);
		menuItemService.save(menuItem53);
		MenuItem menuItem54 = new MenuItem();
		menuItem54.setName("name54");
		menuItem54.setDescription("description54");
		menuItem54.setPrice(10.3);		
		menuItem54.setMenuItemCategory(menuItemCategory2);				
		menuItem54.setSportShop(sportShop2);				
		menuItemService.save(menuItem54);
		MenuItem menuItem55 = new MenuItem();
		menuItem55.setName("name55");
		menuItem55.setDescription("description55");
		menuItem55.setPrice(10.3);		
		menuItem55.setMenuItemCategory(menuItemCategory1);
		menuItem55.setSportShop(sportShop1);
		menuItemService.save(menuItem55);
		MenuItem menuItem56 = new MenuItem();
		menuItem56.setName("name56");
		menuItem56.setDescription("description56");
		menuItem56.setPrice(10.3);		
		menuItem56.setMenuItemCategory(menuItemCategory2);				
		menuItem56.setSportShop(sportShop2);				
		menuItemService.save(menuItem56);
		MenuItem menuItem57 = new MenuItem();
		menuItem57.setName("name57");
		menuItem57.setDescription("description57");
		menuItem57.setPrice(10.3);		
		menuItem57.setMenuItemCategory(menuItemCategory1);
		menuItem57.setSportShop(sportShop1);
		menuItemService.save(menuItem57);
		MenuItem menuItem58 = new MenuItem();
		menuItem58.setName("name58");
		menuItem58.setDescription("description58");
		menuItem58.setPrice(10.3);		
		menuItem58.setMenuItemCategory(menuItemCategory2);				
		menuItem58.setSportShop(sportShop2);				
		menuItemService.save(menuItem58);
		MenuItem menuItem59 = new MenuItem();
		menuItem59.setName("name59");
		menuItem59.setDescription("description59");
		menuItem59.setPrice(10.3);		
		menuItem59.setMenuItemCategory(menuItemCategory1);
		menuItem59.setSportShop(sportShop1);
		menuItemService.save(menuItem59);
		MenuItem menuItem60 = new MenuItem();
		menuItem60.setName("name60");
		menuItem60.setDescription("description60");
		menuItem60.setPrice(10.3);		
		menuItem60.setMenuItemCategory(menuItemCategory2);				
		menuItem60.setSportShop(sportShop2);				
		menuItemService.save(menuItem60);
		MenuItem menuItem61 = new MenuItem();
		menuItem61.setName("name61");
		menuItem61.setDescription("description61");
		menuItem61.setPrice(10.3);		
		menuItem61.setMenuItemCategory(menuItemCategory1);
		menuItem61.setSportShop(sportShop1);
		menuItemService.save(menuItem61);
		MenuItem menuItem62 = new MenuItem();
		menuItem62.setName("name62");
		menuItem62.setDescription("description62");
		menuItem62.setPrice(10.3);		
		menuItem62.setMenuItemCategory(menuItemCategory2);				
		menuItem62.setSportShop(sportShop2);				
		menuItemService.save(menuItem62);
		MenuItem menuItem63 = new MenuItem();
		menuItem63.setName("name63");
		menuItem63.setDescription("description63");
		menuItem63.setPrice(10.3);		
		menuItem63.setMenuItemCategory(menuItemCategory1);
		menuItem63.setSportShop(sportShop1);
		menuItemService.save(menuItem63);
		MenuItem menuItem64 = new MenuItem();
		menuItem64.setName("name64");
		menuItem64.setDescription("description64");
		menuItem64.setPrice(10.3);		
		menuItem64.setMenuItemCategory(menuItemCategory2);				
		menuItem64.setSportShop(sportShop2);				
		menuItemService.save(menuItem64);
		MenuItem menuItem65 = new MenuItem();
		menuItem65.setName("name65");
		menuItem65.setDescription("description65");
		menuItem65.setPrice(10.3);		
		menuItem65.setMenuItemCategory(menuItemCategory1);
		menuItem65.setSportShop(sportShop1);
		menuItemService.save(menuItem65);
		MenuItem menuItem66 = new MenuItem();
		menuItem66.setName("name66");
		menuItem66.setDescription("description66");
		menuItem66.setPrice(10.3);		
		menuItem66.setMenuItemCategory(menuItemCategory2);				
		menuItem66.setSportShop(sportShop2);				
		menuItemService.save(menuItem66);
		MenuItem menuItem67 = new MenuItem();
		menuItem67.setName("name67");
		menuItem67.setDescription("description67");
		menuItem67.setPrice(10.3);		
		menuItem67.setMenuItemCategory(menuItemCategory1);
		menuItem67.setSportShop(sportShop1);
		menuItemService.save(menuItem67);
		MenuItem menuItem68 = new MenuItem();
		menuItem68.setName("name68");
		menuItem68.setDescription("description68");
		menuItem68.setPrice(10.3);		
		menuItem68.setMenuItemCategory(menuItemCategory2);				
		menuItem68.setSportShop(sportShop2);				
		menuItemService.save(menuItem68);
		MenuItem menuItem69 = new MenuItem();
		menuItem69.setName("name69");
		menuItem69.setDescription("description69");
		menuItem69.setPrice(10.3);		
		menuItem69.setMenuItemCategory(menuItemCategory1);
		menuItem69.setSportShop(sportShop1);
		menuItemService.save(menuItem69);
		MenuItem menuItem70 = new MenuItem();
		menuItem70.setName("name70");
		menuItem70.setDescription("description70");
		menuItem70.setPrice(10.3);		
		menuItem70.setMenuItemCategory(menuItemCategory2);				
		menuItem70.setSportShop(sportShop2);				
		menuItemService.save(menuItem70);
		MenuItem menuItem71 = new MenuItem();
		menuItem71.setName("name71");
		menuItem71.setDescription("description71");
		menuItem71.setPrice(10.3);		
		menuItem71.setMenuItemCategory(menuItemCategory1);
		menuItem71.setSportShop(sportShop1);
		menuItemService.save(menuItem71);
		MenuItem menuItem72 = new MenuItem();
		menuItem72.setName("name72");
		menuItem72.setDescription("description72");
		menuItem72.setPrice(10.3);		
		menuItem72.setMenuItemCategory(menuItemCategory2);				
		menuItem72.setSportShop(sportShop2);				
		menuItemService.save(menuItem72);
		MenuItem menuItem73 = new MenuItem();
		menuItem73.setName("name73");
		menuItem73.setDescription("description73");
		menuItem73.setPrice(10.3);		
		menuItem73.setMenuItemCategory(menuItemCategory1);
		menuItem73.setSportShop(sportShop1);
		menuItemService.save(menuItem73);
		MenuItem menuItem74 = new MenuItem();
		menuItem74.setName("name74");
		menuItem74.setDescription("description74");
		menuItem74.setPrice(10.3);		
		menuItem74.setMenuItemCategory(menuItemCategory2);				
		menuItem74.setSportShop(sportShop2);				
		menuItemService.save(menuItem74);
		MenuItem menuItem75 = new MenuItem();
		menuItem75.setName("name75");
		menuItem75.setDescription("description75");
		menuItem75.setPrice(10.3);		
		menuItem75.setMenuItemCategory(menuItemCategory1);
		menuItem75.setSportShop(sportShop1);
		menuItemService.save(menuItem75);
		MenuItem menuItem76 = new MenuItem();
		menuItem76.setName("name76");
		menuItem76.setDescription("description76");
		menuItem76.setPrice(10.3);		
		menuItem76.setMenuItemCategory(menuItemCategory2);				
		menuItem76.setSportShop(sportShop2);				
		menuItemService.save(menuItem76);
		MenuItem menuItem77 = new MenuItem();
		menuItem77.setName("name77");
		menuItem77.setDescription("description77");
		menuItem77.setPrice(10.3);		
		menuItem77.setMenuItemCategory(menuItemCategory1);
		menuItem77.setSportShop(sportShop1);
		menuItemService.save(menuItem77);
		MenuItem menuItem78 = new MenuItem();
		menuItem78.setName("name78");
		menuItem78.setDescription("description78");
		menuItem78.setPrice(10.3);		
		menuItem78.setMenuItemCategory(menuItemCategory2);				
		menuItem78.setSportShop(sportShop2);				
		menuItemService.save(menuItem78);
		MenuItem menuItem79 = new MenuItem();
		menuItem79.setName("name79");
		menuItem79.setDescription("description79");
		menuItem79.setPrice(10.3);		
		menuItem79.setMenuItemCategory(menuItemCategory1);
		menuItem79.setSportShop(sportShop1);
		menuItemService.save(menuItem79);
		MenuItem menuItem80 = new MenuItem();
		menuItem80.setName("name80");
		menuItem80.setDescription("description80");
		menuItem80.setPrice(10.3);		
		menuItem80.setMenuItemCategory(menuItemCategory2);				
		menuItem80.setSportShop(sportShop2);				
		menuItemService.save(menuItem80);
		MenuItem menuItem81 = new MenuItem();
		menuItem81.setName("name81");
		menuItem81.setDescription("description81");
		menuItem81.setPrice(10.3);		
		menuItem81.setMenuItemCategory(menuItemCategory1);
		menuItem81.setSportShop(sportShop1);
		menuItemService.save(menuItem81);
		MenuItem menuItem82 = new MenuItem();
		menuItem82.setName("name82");
		menuItem82.setDescription("description82");
		menuItem82.setPrice(10.3);		
		menuItem82.setMenuItemCategory(menuItemCategory2);				
		menuItem82.setSportShop(sportShop2);				
		menuItemService.save(menuItem82);
		MenuItem menuItem83 = new MenuItem();
		menuItem83.setName("name83");
		menuItem83.setDescription("description83");
		menuItem83.setPrice(10.3);		
		menuItem83.setMenuItemCategory(menuItemCategory1);
		menuItem83.setSportShop(sportShop1);
		menuItemService.save(menuItem83);
		MenuItem menuItem84 = new MenuItem();
		menuItem84.setName("name84");
		menuItem84.setDescription("description84");
		menuItem84.setPrice(10.3);		
		menuItem84.setMenuItemCategory(menuItemCategory2);				
		menuItem84.setSportShop(sportShop2);				
		menuItemService.save(menuItem84);
		MenuItem menuItem85 = new MenuItem();
		menuItem85.setName("name85");
		menuItem85.setDescription("description85");
		menuItem85.setPrice(10.3);		
		menuItem85.setMenuItemCategory(menuItemCategory1);
		menuItem85.setSportShop(sportShop1);
		menuItemService.save(menuItem85);
		MenuItem menuItem86 = new MenuItem();
		menuItem86.setName("name86");
		menuItem86.setDescription("description86");
		menuItem86.setPrice(10.3);		
		menuItem86.setMenuItemCategory(menuItemCategory2);				
		menuItem86.setSportShop(sportShop2);				
		menuItemService.save(menuItem86);
		MenuItem menuItem87 = new MenuItem();
		menuItem87.setName("name87");
		menuItem87.setDescription("description87");
		menuItem87.setPrice(10.3);		
		menuItem87.setMenuItemCategory(menuItemCategory1);
		menuItem87.setSportShop(sportShop1);
		menuItemService.save(menuItem87);
		MenuItem menuItem88 = new MenuItem();
		menuItem88.setName("name88");
		menuItem88.setDescription("description88");
		menuItem88.setPrice(10.3);		
		menuItem88.setMenuItemCategory(menuItemCategory2);				
		menuItem88.setSportShop(sportShop2);				
		menuItemService.save(menuItem88);
		MenuItem menuItem89 = new MenuItem();
		menuItem89.setName("name89");
		menuItem89.setDescription("description89");
		menuItem89.setPrice(10.3);		
		menuItem89.setMenuItemCategory(menuItemCategory1);
		menuItem89.setSportShop(sportShop1);
		menuItemService.save(menuItem89);
		MenuItem menuItem90 = new MenuItem();
		menuItem90.setName("name90");
		menuItem90.setDescription("description90");
		menuItem90.setPrice(10.3);		
		menuItem90.setMenuItemCategory(menuItemCategory2);				
		menuItem90.setSportShop(sportShop2);				
		menuItemService.save(menuItem90);
		MenuItem menuItem91 = new MenuItem();
		menuItem91.setName("name91");
		menuItem91.setDescription("description91");
		menuItem91.setPrice(10.3);		
		menuItem91.setMenuItemCategory(menuItemCategory1);
		menuItem91.setSportShop(sportShop1);
		menuItemService.save(menuItem91);
		MenuItem menuItem92 = new MenuItem();
		menuItem92.setName("name92");
		menuItem92.setDescription("description92");
		menuItem92.setPrice(10.3);		
		menuItem92.setMenuItemCategory(menuItemCategory2);				
		menuItem92.setSportShop(sportShop2);				
		menuItemService.save(menuItem92);
		MenuItem menuItem93 = new MenuItem();
		menuItem93.setName("name93");
		menuItem93.setDescription("description93");
		menuItem93.setPrice(10.3);		
		menuItem93.setMenuItemCategory(menuItemCategory1);
		menuItem93.setSportShop(sportShop1);
		menuItemService.save(menuItem93);
		MenuItem menuItem94 = new MenuItem();
		menuItem94.setName("name94");
		menuItem94.setDescription("description94");
		menuItem94.setPrice(10.3);		
		menuItem94.setMenuItemCategory(menuItemCategory2);				
		menuItem94.setSportShop(sportShop2);				
		menuItemService.save(menuItem94);
		MenuItem menuItem95 = new MenuItem();
		menuItem95.setName("name95");
		menuItem95.setDescription("description95");
		menuItem95.setPrice(10.3);		
		menuItem95.setMenuItemCategory(menuItemCategory1);
		menuItem95.setSportShop(sportShop1);
		menuItemService.save(menuItem95);
		MenuItem menuItem96 = new MenuItem();
		menuItem96.setName("name96");
		menuItem96.setDescription("description96");
		menuItem96.setPrice(10.3);		
		menuItem96.setMenuItemCategory(menuItemCategory2);				
		menuItem96.setSportShop(sportShop2);				
		menuItemService.save(menuItem96);
		MenuItem menuItem97 = new MenuItem();
		menuItem97.setName("name97");
		menuItem97.setDescription("description97");
		menuItem97.setPrice(10.3);		
		menuItem97.setMenuItemCategory(menuItemCategory1);
		menuItem97.setSportShop(sportShop1);
		menuItemService.save(menuItem97);
		MenuItem menuItem98 = new MenuItem();
		menuItem98.setName("name98");
		menuItem98.setDescription("description98");
		menuItem98.setPrice(10.3);		
		menuItem98.setMenuItemCategory(menuItemCategory2);				
		menuItem98.setSportShop(sportShop2);				
		menuItemService.save(menuItem98);
		MenuItem menuItem99 = new MenuItem();
		menuItem99.setName("name99");
		menuItem99.setDescription("description99");
		menuItem99.setPrice(10.3);		
		menuItem99.setMenuItemCategory(menuItemCategory1);
		menuItem99.setSportShop(sportShop1);
		menuItemService.save(menuItem99);
		MenuItem menuItem100 = new MenuItem();
		menuItem100.setName("name100");
		menuItem100.setDescription("description100");
		menuItem100.setPrice(10.3);		
		menuItem100.setMenuItemCategory(menuItemCategory2);				
		menuItem100.setSportShop(sportShop2);				
		menuItemService.save(menuItem100);
		MenuItem menuItem101 = new MenuItem();
		menuItem101.setName("name101");
		menuItem101.setDescription("description101");
		menuItem101.setPrice(10.3);		
		menuItem101.setMenuItemCategory(menuItemCategory1);
		menuItem101.setSportShop(sportShop1);
		menuItemService.save(menuItem101);
		MenuItem menuItem102 = new MenuItem();
		menuItem102.setName("name102");
		menuItem102.setDescription("description102");
		menuItem102.setPrice(10.3);		
		menuItem102.setMenuItemCategory(menuItemCategory2);				
		menuItem102.setSportShop(sportShop2);				
		menuItemService.save(menuItem102);
		MenuItem menuItem103 = new MenuItem();
		menuItem103.setName("name103");
		menuItem103.setDescription("description103");
		menuItem103.setPrice(10.3);		
		menuItem103.setMenuItemCategory(menuItemCategory1);
		menuItem103.setSportShop(sportShop1);
		menuItemService.save(menuItem103);
		MenuItem menuItem104 = new MenuItem();
		menuItem104.setName("name104");
		menuItem104.setDescription("description104");
		menuItem104.setPrice(10.3);		
		menuItem104.setMenuItemCategory(menuItemCategory2);				
		menuItem104.setSportShop(sportShop2);				
		menuItemService.save(menuItem104);
		MenuItem menuItem105 = new MenuItem();
		menuItem105.setName("name105");
		menuItem105.setDescription("description105");
		menuItem105.setPrice(10.3);		
		menuItem105.setMenuItemCategory(menuItemCategory1);
		menuItem105.setSportShop(sportShop1);
		menuItemService.save(menuItem105);
		MenuItem menuItem106 = new MenuItem();
		menuItem106.setName("name106");
		menuItem106.setDescription("description106");
		menuItem106.setPrice(10.3);		
		menuItem106.setMenuItemCategory(menuItemCategory2);				
		menuItem106.setSportShop(sportShop2);				
		menuItemService.save(menuItem106);
		MenuItem menuItem107 = new MenuItem();
		menuItem107.setName("name107");
		menuItem107.setDescription("description107");
		menuItem107.setPrice(10.3);		
		menuItem107.setMenuItemCategory(menuItemCategory1);
		menuItem107.setSportShop(sportShop1);
		menuItemService.save(menuItem107);
		MenuItem menuItem108 = new MenuItem();
		menuItem108.setName("name108");
		menuItem108.setDescription("description108");
		menuItem108.setPrice(10.3);		
		menuItem108.setMenuItemCategory(menuItemCategory2);				
		menuItem108.setSportShop(sportShop2);				
		menuItemService.save(menuItem108);
		MenuItem menuItem109 = new MenuItem();
		menuItem109.setName("name109");
		menuItem109.setDescription("description109");
		menuItem109.setPrice(10.3);		
		menuItem109.setMenuItemCategory(menuItemCategory1);
		menuItem109.setSportShop(sportShop1);
		menuItemService.save(menuItem109);
		MenuItem menuItem110 = new MenuItem();
		menuItem110.setName("name110");
		menuItem110.setDescription("description110");
		menuItem110.setPrice(10.3);		
		menuItem110.setMenuItemCategory(menuItemCategory2);				
		menuItem110.setSportShop(sportShop2);				
		menuItemService.save(menuItem110);
		MenuItem menuItem111 = new MenuItem();
		menuItem111.setName("name111");
		menuItem111.setDescription("description111");
		menuItem111.setPrice(10.3);		
		menuItem111.setMenuItemCategory(menuItemCategory1);
		menuItem111.setSportShop(sportShop1);
		menuItemService.save(menuItem111);
		MenuItem menuItem112 = new MenuItem();
		menuItem112.setName("name112");
		menuItem112.setDescription("description112");
		menuItem112.setPrice(10.3);		
		menuItem112.setMenuItemCategory(menuItemCategory2);				
		menuItem112.setSportShop(sportShop2);				
		menuItemService.save(menuItem112);
		MenuItem menuItem113 = new MenuItem();
		menuItem113.setName("name113");
		menuItem113.setDescription("description113");
		menuItem113.setPrice(10.3);		
		menuItem113.setMenuItemCategory(menuItemCategory1);
		menuItem113.setSportShop(sportShop1);
		menuItemService.save(menuItem113);
		MenuItem menuItem114 = new MenuItem();
		menuItem114.setName("name114");
		menuItem114.setDescription("description114");
		menuItem114.setPrice(10.3);		
		menuItem114.setMenuItemCategory(menuItemCategory2);				
		menuItem114.setSportShop(sportShop2);				
		menuItemService.save(menuItem114);
		MenuItem menuItem115 = new MenuItem();
		menuItem115.setName("name115");
		menuItem115.setDescription("description115");
		menuItem115.setPrice(10.3);		
		menuItem115.setMenuItemCategory(menuItemCategory1);
		menuItem115.setSportShop(sportShop1);
		menuItemService.save(menuItem115);
		MenuItem menuItem116 = new MenuItem();
		menuItem116.setName("name116");
		menuItem116.setDescription("description116");
		menuItem116.setPrice(10.3);		
		menuItem116.setMenuItemCategory(menuItemCategory2);				
		menuItem116.setSportShop(sportShop2);				
		menuItemService.save(menuItem116);
		MenuItem menuItem117 = new MenuItem();
		menuItem117.setName("name117");
		menuItem117.setDescription("description117");
		menuItem117.setPrice(10.3);		
		menuItem117.setMenuItemCategory(menuItemCategory1);
		menuItem117.setSportShop(sportShop1);
		menuItemService.save(menuItem117);
		MenuItem menuItem118 = new MenuItem();
		menuItem118.setName("name118");
		menuItem118.setDescription("description118");
		menuItem118.setPrice(10.3);		
		menuItem118.setMenuItemCategory(menuItemCategory2);				
		menuItem118.setSportShop(sportShop2);				
		menuItemService.save(menuItem118);
		MenuItem menuItem119 = new MenuItem();
		menuItem119.setName("name119");
		menuItem119.setDescription("description119");
		menuItem119.setPrice(10.3);		
		menuItem119.setMenuItemCategory(menuItemCategory1);
		menuItem119.setSportShop(sportShop1);
		menuItemService.save(menuItem119);
		MenuItem menuItem120 = new MenuItem();
		menuItem120.setName("name120");
		menuItem120.setDescription("description120");
		menuItem120.setPrice(10.3);		
		menuItem120.setMenuItemCategory(menuItemCategory2);				
		menuItem120.setSportShop(sportShop2);				
		menuItemService.save(menuItem120);
		MenuItem menuItem121 = new MenuItem();
		menuItem121.setName("name121");
		menuItem121.setDescription("description121");
		menuItem121.setPrice(10.3);		
		menuItem121.setMenuItemCategory(menuItemCategory1);
		menuItem121.setSportShop(sportShop1);
		menuItemService.save(menuItem121);
		MenuItem menuItem122 = new MenuItem();
		menuItem122.setName("name122");
		menuItem122.setDescription("description122");
		menuItem122.setPrice(10.3);		
		menuItem122.setMenuItemCategory(menuItemCategory2);				
		menuItem122.setSportShop(sportShop2);				
		menuItemService.save(menuItem122);
		MenuItem menuItem123 = new MenuItem();
		menuItem123.setName("name123");
		menuItem123.setDescription("description123");
		menuItem123.setPrice(10.3);		
		menuItem123.setMenuItemCategory(menuItemCategory1);
		menuItem123.setSportShop(sportShop1);
		menuItemService.save(menuItem123);
		MenuItem menuItem124 = new MenuItem();
		menuItem124.setName("name124");
		menuItem124.setDescription("description124");
		menuItem124.setPrice(10.3);		
		menuItem124.setMenuItemCategory(menuItemCategory2);				
		menuItem124.setSportShop(sportShop2);				
		menuItemService.save(menuItem124);
		MenuItem menuItem125 = new MenuItem();
		menuItem125.setName("name125");
		menuItem125.setDescription("description125");
		menuItem125.setPrice(10.3);		
		menuItem125.setMenuItemCategory(menuItemCategory1);
		menuItem125.setSportShop(sportShop1);
		menuItemService.save(menuItem125);
		MenuItem menuItem126 = new MenuItem();
		menuItem126.setName("name126");
		menuItem126.setDescription("description126");
		menuItem126.setPrice(10.3);		
		menuItem126.setMenuItemCategory(menuItemCategory2);				
		menuItem126.setSportShop(sportShop2);				
		menuItemService.save(menuItem126);
		MenuItem menuItem127 = new MenuItem();
		menuItem127.setName("name127");
		menuItem127.setDescription("description127");
		menuItem127.setPrice(10.3);		
		menuItem127.setMenuItemCategory(menuItemCategory1);
		menuItem127.setSportShop(sportShop1);
		menuItemService.save(menuItem127);
		MenuItem menuItem128 = new MenuItem();
		menuItem128.setName("name128");
		menuItem128.setDescription("description128");
		menuItem128.setPrice(10.3);		
		menuItem128.setMenuItemCategory(menuItemCategory2);				
		menuItem128.setSportShop(sportShop2);				
		menuItemService.save(menuItem128);

	}
	
}
